---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: client-app01
  name: client-app01
spec:
  containers:
  - command:
    - sleep
    - "2147483648"
    image: cockroachdb/cockroach:v2.0.3
    imagePullPolicy: IfNotPresent
    name: client-app01
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/secrets/mydb01-binding
      name: mydb01-binding
    env:
    - name: "COCKROACH_URL"
      valueFrom:
        secretKeyRef:
          name: mydb01-binding
          key: uri
  volumes:
    - name: mydb01-binding
      secret:
        secretName: mydb01-binding
    - emptyDir: {}
      name: client-certs
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: mydb01-binding
spec:
  instanceRef:
    name: mydb01
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: mydb01
spec:
  clusterServiceClassExternalName: cockroachdb
  clusterServicePlanExternalName: default
